Repository IIITKalyaniFOSC/MediCare-Prime, pull requests merged in 2021-07, with the labels that each got.

#41 Push to deploy updates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new-disease.md
  .github/labels.json
  .github/workflows/issue-label.yml
  LICENSE
  app.py
  contributing.md
Labels: deploy

#45 added some badges in the README
  README.md
Labels: LGMSOC21, 🟩 Level1

#40 updating heart-disease webpage as per #38
  templates/heartDisease.html
Labels: LGMSOC21, 🟨 Level2

#56 Parkinson's Disease Prediction
  app.py
  models/ParkinsonDisease/Parkinson's_Disease_Prediction.ipynb
  models/ParkinsonDisease/parkinson.pickle
  models/ParkinsonDisease/parkinsons.csv
  templates/index.html
  templates/parkinsonDisease.html
  templates/predictParkinson.html
Labels: devincept'21

#59 Footer now in proper place and Github Link Working
  templates/index.html
Labels: devincept'21

#62 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: devincept'21

#63 Update README.md
  README.md
Labels: devincept'21

#66 Thyroid Disease Prediction
  app.py
  models/ThyroidDisease/Thyroid_Disease_Prediction.ipynb
  models/ThyroidDisease/thyroid.csv
  models/ThyroidDisease/thyroid.pickle
  templates/index.html
  templates/predictThyroid.html
  templates/thyroidDisease.html
Labels: devincept'21

#71 Made title bar dynamic
  templates/breastCancer.html
  templates/covid.htm
  templates/dengue.html
  templates/diabetes.html
  templates/heartDisease.html
  templates/index.html
  templates/index_content.html
  templates/kidney.html
  templates/malaria.html
  templates/parkinsonDisease.html
  templates/predictCovid.htm
  templates/predictDengue.html
  templates/predictDiabetes.html
  templates/predictKidney.html
  templates/predictMalaria.html
  templates/predictParkinson.html
  templates/predictThyroid.html
  templates/thyroidDisease.html
Labels: 🟨 Level2
